apiVersion: v1
kind: Service
metadata:
  name: upf
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: free5gc-upf
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8805
      targetPort: 8805
      protocol: UDP
